<?php

/**
 * @file
 * Provides administrative enhancements for the SolKit Distribution
 */

include_once 'solkit_admin.features.inc';

/**
 * Implements hook_page_build().
 */
function solkit_admin_page_build(&$page) {
  $path = drupal_get_path('module', 'solkit_admin');
  $page['page_bottom']['solkit_admin'] = array(
    '#attached' => array(),
  );
  $attached = &$page['page_bottom']['solkit_admin']['#attached'];
  $options = array('every_page' => TRUE);

  // Attach admin css.
  $attached['css'][$path . '/css/solkit_admin.css'] = $options;
}


/**
 * Implements hook_preprocess_panels_pane().
 */
function solkit_admin_preprocess_panels_pane(&$variables) {
  $pane = $variables['pane'];
  // If pane is an entity form field, use the field title as the pane title.
  if ($pane->type == 'entity_form_field') {
    // Check if the pane is in the sidebar.
    if (!empty($variables['display'])) {
      if (in_array($pane->pid, $variables['display']->panels['sidebar'])) {
        $field = reset($variables['content']);
        if (isset($field['#language'])) {
          if (isset($field[$field['#language']]['#title'])) {
            $variables['title'] = $field[$field['#language']]['#title'];
            if ($field[$field['#language']]['#required']) {
              $variables['title'] .= '<span class="form-required" title="This field is required.">*</span>';
            }
          }
        }
      }
    }
  }
}
